### ISSUE TITLE
User Profile implementation

### ISSUE THREAD

**Issue by grambas** [grambas/guess-a-song#61]
** User can save / edit game name **
** System generates and saves uuid **

**Comment by burnsan** [comment]
By "game name" do we mean the name of a player or the name of the game room?

**Comment by grambas** [comment]
The name of the player

**Comment by grambas** [comment]
For uuid you can use String uniqueID= Settings.Secure.getString(getApplicationContext().getContentResolver(),
                Settings.Secure.ANDROID_ID);
