### ISSUE TITLE
Figure Out APIs

### ISSUE THREAD

**Issue by burnsan** [grambas/guess-a-song#7]
Identify and test any and all APIs that will be used in the project.

**Comment by grambas** [comment]
**PubNub**
Andoird SDK Documentation - https://www.pubnub.com/docs/android-java/pubnub-java-sdk
Realtime Chat App Tutorial/Exampe - https://www.pubnub.com/tutorials/android/getting-started/
Tested in #5  #6

**Comment by burnsan** [comment]
I think we've got all of our APIs, Frameworks, and Libraries figured out. Setting this to the Review/QA pipeline to give everyone a chance to chime in. Otherwise, I'm calling this issue closed.
